spring:
  application:
    name: Backend
  datasource:
    url: jdbc:mysql://localhost:3306/delivery-app
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
  flyway:
    user: root
    password:
    schemas: delivery-app
    url: jdbc:mysql://localhost:3306/delivery-app
server:
  port: 8081